=== ApexLiberta/cbe/tmp/sources/schema/src.sch.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Main Schema",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description": "Name of the game"
		},
		"version": {
			"type": "number",
			"description": "Version of the scraper"
		},
		"gistId": {
			"type": "string",
			"description": "Optional Gist ID for the scraper code"
		},
		"matches": {
			"type": "string",
			"description": "URL pattern to match game pages"
		},
		"selectors": {
			"$ref": "./sels.sch.json"
		}
	},
	"required": ["name", "version", "matches", "selectors"]
}

=== ApexLiberta/cbe/tmp/sources/store_epicgames_com.json
{
	"name": "epic",
	"version": 0.1,
	"gistId": "",
	"matches": "*://*.epicgames.com/en-US/p/*",
	"selectors": {
		"name": {
			"selector": "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-1rn9p2c div.css-5du7g4 div.css-i9gxme h1.eds_1ypbntd0.eds_1ypbntd3.eds_1ypbntdk.css-12s1vua",
			"type": "text"
		},
		"description": {
			"selector": "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-2tyhrd div.css-1nqq6xy div.css-qemfat div.css-usl2mg div.css-3r3brs div.css-j7qwjs div.css-16l4hro span.eds_1ypbntd0.eds_1ypbntd9.eds_1ypbntdk.css-12s1vua div.css-lgj0h8 div.css-1myreog",
			"type": "text"
		},
		"genres": {
			"selector": "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-2tyhrd div.css-1nqq6xy div.css-qemfat div.css-usl2mg div.css-3r3brs div.css-j7qwjs div.css-16l4hro div.css-1wrgvz3 div.css-8f0505 div.css-j7qwjs div.css-11w1nwr div.eds_1cgaabk0.eds_1cgaabk2.eds_1cgaabka.eds_1cgaabkb.eds_1cgaabk5.eds_1tt68zf0.eds_1tt68zf7",
			"type": "link"
		},
		"features": {
            "selector": "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-2tyhrd div.css-1nqq6xy div.css-qemfat div.css-usl2mg div.css-3r3brs div.css-j7qwjs div.css-16l4hro div.css-1wrgvz3 div.css-8f0505 div.css-j7qwjs div.css-11w1nwr div.eds_1cgaabk0.eds_1cgaabk2.eds_1cgaabka.eds_1cgaabkb.eds_1cgaabk5.eds_1tt68zf0.eds_1tt68zf7",
            "type": "link"
        },
		"developer": {
            "selector":  "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-2tyhrd div.css-1nqq6xy aside.css-566nsd div.css-1gmuxco div.css-1q94rgb div.css-1ofqig9 div.css-s97i32 div.css-1o0y1dn div.css-btns76 span.eds_1ypbntd0.eds_1ypbntdc.eds_1ypbntdk.css-12s1vua",
            "type": "0 string split comma space"
        },
		"publisher": {
            "selector": "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-2tyhrd div.css-1nqq6xy aside.css-566nsd div.css-1gmuxco div.css-1q94rgb div.css-1ofqig9 div.css-s97i32 div.css-1o0y1dn div.css-btns76 span.eds_1ypbntd0.eds_1ypbntdc.eds_1ypbntdk.css-12s1vua",
            "type":"1 string split comma space"
        },
		"releaseDate": {
            "selector": "html body div#dieselReactWrapper.en-US-locale div.eds_xd1k8g0 div.isBrowser.css-2nhytu div.css-1vplx76 main.css-1pmr3eb div.css-1dnikhe div.css-1dacand div.css-s45c7f div.css-r2r3m1 div.css-j7qwjs div.css-2tyhrd div.css-1nqq6xy aside.css-566nsd div.css-1gmuxco div.css-1q94rgb div.css-1ofqig9 div.css-s97i32 div.css-1o0y1dn div.css-btns76 span.eds_1ypbntd0.eds_1ypbntdc.eds_1ypbntdk.css-12s1vua time",
            "type": "text"
        }
	}
}

=== ApexLiberta/cbe/tmp/sources/bin/store_steampowered_com.json
{
	"name": "steam",
    "version": 0.1,
    "gistId": "",
    "matches": "*://*.steampowered.com/app/*",
	"selectors": {
		"name": {
			"selector": "html.responsive body.v6.app.game_bg.application.responsive_page div.responsive_page_frame.with_header div.responsive_page_content div#responsive_page_template_content.responsive_page_template_content div.game_page_background.game div#tabletGrid.tablet_grid div.page_content_ctn div.page_title_area.game_title_area.page_content div.apphub_HomeHeaderContent div.apphub_HeaderStandardTop div#appHubAppName.apphub_AppName",
			"type": "extTxt"
		},
		"description": {
			"selector": "html.responsive body.v6.app.game_bg.application.responsive_page div.responsive_page_frame.with_header div.responsive_page_content div#responsive_page_template_content.responsive_page_template_content div.game_page_background.game div#tabletGrid.tablet_grid div.page_content_ctn div.block.game_media_and_summary_ctn div.game_background_glow div#game_highlights.block_content.page_content div.rightcol div.glance_ctn div.game_description_snippet",
			"type": "extTxt"
		},
		"releaseDate": {
			"selector": "html.responsive body.v6.app.game_bg.application.responsive_page div.responsive_page_frame.with_header div.responsive_page_content div#responsive_page_template_content.responsive_page_template_content div.game_page_background.game div#tabletGrid.tablet_grid div.page_content_ctn div.block.game_media_and_summary_ctn div.game_background_glow div#game_highlights.block_content.page_content div.rightcol div.glance_ctn div.glance_ctn_responsive_left div.release_date div.date",
			"type":"extTxt"
		},
		"developers": {
			"selector": "html.responsive body.v6.app.game_bg.application.responsive_page div.responsive_page_frame.with_header div.responsive_page_content div#responsive_page_template_content.responsive_page_template_content div.game_page_background.game div#tabletGrid.tablet_grid div.page_content_ctn div.block.game_media_and_summary_ctn div.game_background_glow div#game_highlights.block_content.page_content div.rightcol div.glance_ctn div.glance_ctn_responsive_left div.dev_row div#developers_list.summary.column",
			"type": "extLnksTxt"
		},
		"publishers": {
			"selector": "html.responsive body.v6.app.game_bg.application.responsive_page div.responsive_page_frame.with_header div.responsive_page_content div#responsive_page_template_content.responsive_page_template_content div.game_page_background.game div#tabletGrid.tablet_grid div.page_content_ctn div.block.game_media_and_summary_ctn div.game_background_glow div#game_highlights.block_content.page_content div.rightcol div.glance_ctn div.glance_ctn_responsive_left div.dev_row div.summary.column",
			"type": "extTxtArrBySiblMch"
		},
		"tags": {
			"selector": "html.responsive body.v6.app.game_bg.application.responsive_page div.responsive_page_frame.with_header div.responsive_page_content div#responsive_page_template_content.responsive_page_template_content div.game_page_background.game div#tabletGrid.tablet_grid div.page_content_ctn div.block.game_media_and_summary_ctn div.game_background_glow div#game_highlights.block_content.page_content div.rightcol div.glance_ctn div#glanceCtnResponsiveRight.glance_ctn_responsive_right div.glance_tags_ctn.popular_tags_ctn div.glance_tags.popular_tags",
			"type": "extLnksTxt"
		}
	}
}
